name: Code Agent Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    name: Analyze Code with AI Agent
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Run Code Agent
        uses: potproject/code-agent@v0.2.2
        with:
          # Анализ кода и предложение улучшений
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Опциональные параметры
          # model: 'gpt-4' # или 'gpt-3.5-turbo'
          # temperature: 0.7
          # max_tokens: 2000
          
          # Типы анализа
          analyze_security: true
          analyze_performance: true
          analyze_best_practices: true
          analyze_documentation: true
          
          # Автоматические исправления
          auto_fix: false # Установите true для автоматических PR с исправлениями
          
          # Фильтры файлов
          include_patterns: |
            **/*.js
            **/*.jsx
            **/*.ts
            **/*.tsx
            **/*.json
            **/*.yml
            **/*.yaml
          
          exclude_patterns: |
            node_modules/**
            .next/**
            build/**
            dist/**
            coverage/**
            **/*.min.js
            **/*.test.js
            **/*.spec.js
          
          # Конфигурация отчетов
          comment_on_pr: true
          create_issues: true
          severity_threshold: 'medium' # low, medium, high
          
          # Дополнительные правила
          custom_rules: |
            - Проверить использование 'use client' директивы в компонентах
            - Убедиться в наличии обработки ошибок
            - Проверить оптимизацию изображений Next.js
            - Валидация TypeScript типов
            - Проверка доступности (a11y)
            - Оптимизация bundle size
            - Проверка SEO мета-тегов
            - Валидация API endpoints
            - Проверка безопасности JWT
            - Оптимизация React рендеринга
          
          # Игнорировать определенные проблемы
          ignore_issues: |
            - console.log в development режиме
            - TODO комментарии
            - Экспериментальные Next.js features
      
      - name: Upload Analysis Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-analysis-report
          path: |
            code-agent-report.json
            code-agent-report.html
          retention-days: 30
      
      - name: Check Analysis Results
        run: |
          if [ -f "code-agent-report.json" ]; then
            echo "📊 Code Analysis Complete"
            echo "=============================="
            cat code-agent-report.json | jq '.summary'
          fi

  # Дополнительная job для критических проблем
  critical-issues:
    needs: code-analysis
    runs-on: ubuntu-latest
    if: failure()
    
    steps:
      - name: Create Critical Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Critical Code Issues Found',
              body: `Code Agent обнаружил критические проблемы в коде.
              
              **Commit:** ${context.sha}
              **Branch:** ${context.ref}
              **Workflow:** ${context.workflow}
              
              Пожалуйста, проверьте [результаты анализа](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}).`,
              labels: ['critical', 'code-quality', 'automated']
            });