name: Enhanced Security Scanning

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Ежедневное сканирование в 2:00 UTC
    - cron: '0 2 * * *'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  # Сканирование на утечку секретов
  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Полная история для глубокого сканирования

      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Gitleaks Action
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for .env files
        run: |
          echo "🔍 Checking for .env files that might contain secrets..."

          # Список файлов которые НЕ должны быть в репозитории
          FORBIDDEN_FILES=(
            ".env"
            ".env.local"
            ".env.production"
            ".env.development"
            ".env.staging"
          )

          FOUND_ISSUES=0

          for file in "${FORBIDDEN_FILES[@]}"; do
            if [ -f "$file" ]; then
              echo "❌ CRITICAL: Found $file in repository!"
              echo "   This file should NEVER be committed!"
              FOUND_ISSUES=1
            fi
          done

          # Проверка что .env файлы в .gitignore
          if ! grep -q "^\.env" .gitignore; then
            echo "❌ WARNING: .env not found in .gitignore!"
            FOUND_ISSUES=1
          fi

          # Проверка на hardcoded secrets в коде
          echo "🔍 Scanning for hardcoded secrets..."

          # Паттерны для поиска
          SECRET_PATTERNS=(
            "PRIVATE_KEY"
            "API_KEY"
            "SECRET_KEY"
            "PASSWORD"
            "TOKEN"
            "GEMINI_API_KEY"
            "sk-[a-zA-Z0-9]{48}"
            "AIza[0-9A-Za-z-_]{35}"
          )

          for pattern in "${SECRET_PATTERNS[@]}"; do
            if grep -r "$pattern" . --include="*.js" --include="*.ts" --include="*.jsx" --include="*.tsx" --exclude-dir=node_modules --exclude-dir=.git | grep -v ".env.example"; then
              echo "❌ WARNING: Found potential secret pattern: $pattern"
              FOUND_ISSUES=1
            fi
          done

          if [ $FOUND_ISSUES -eq 1 ]; then
            echo "⚠️ Security issues found! Please review and fix."
            exit 1
          else
            echo "✅ No obvious security issues found."
          fi

  # CodeQL анализ с Bundle
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 360

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript', 'typescript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CodeQL Bundle
        uses: advanced-security/codeql-bundle-action@v2.2.0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: +security-extended,security-and-quality
          # Использование bundle для расширенного анализа
          tools: latest

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: '/language:${{matrix.language}}'
          upload: true

  # Дополнительные проверки безопасности
  security-checks:
    name: Additional Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: |
          npm audit --production
          npm audit --audit-level=moderate
        continue-on-error: true

      - name: Run Snyk Security Scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'NeuroExpert'
          path: '.'
          format: 'HTML'
          args: >
            --enableRetired
            --enableExperimental

      - name: Upload OWASP results
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: reports/

  # Проверка Docker образов (если есть)
  docker-security:
    name: Docker Security Scan
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'docker') || github.event_name == 'schedule'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  # Финальный отчет
  security-report:
    name: Security Report
    runs-on: ubuntu-latest
    needs: [secret-scanning, codeql-analysis, security-checks]
    if: always()

    steps:
      - name: Create Security Report
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const jobs = ${{ toJson(needs) }};
            let comment = '## 🔒 Security Scan Report\n\n';

            comment += '| Check | Status |\n';
            comment += '|-------|--------|\n';

            for (const [job, result] of Object.entries(jobs)) {
              const status = result.result === 'success' ? '✅' : '❌';
              const jobName = job.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
              comment += `| ${jobName} | ${status} |\n`;
            }

            comment += '\n### 🔍 Scan Details\n';
            comment += '- Secret Scanning: TruffleHog + Gitleaks\n';
            comment += '- Code Analysis: CodeQL with security-extended queries\n';
            comment += '- Dependencies: npm audit + Snyk + OWASP\n';

            comment += '\n### ⚠️ Important Reminders\n';
            comment += '- Never commit `.env` files\n';
            comment += '- Always use environment variables for secrets\n';
            comment += '- Review all security warnings before merging\n';

            // Комментируем только в PR
            if (context.eventName === 'pull_request') {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
